owner: ziodotsh
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
    # Servers
  - name: "Zio DE01 (Hetzner)"
    url: https://de01.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-germany_1f1e9-1f1ea.png
  - name: "Zio DE02 (Hetzner)"
    url: https://de02.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-germany_1f1e9-1f1ea.png
  - name: "Zio GB01 (Virgin Media)"
    url: https://gb01.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-united-kingdom_1f1ec-1f1e7.png
  - name: "Zio GB02 (KCOM)"
    url: https://gb02.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-united-kingdom_1f1ec-1f1e7.png
  - name: "Zio NL01 (Scaleway)"
    url: https://nl01.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-netherlands_1f1f3-1f1f1.png

    # Websites
  - name: Gitea
    url: https://git.zio.sh
    icon: https://git.zio.sh/assets/img/logo.svg
  - name: OSTree Repo
    url: https://ostree.zio.sh

status-website:
  cname: uptime.zio.sh
  css: >
    .live-status > article:nth-child(5) { margin-bottom: 1em; }
  name: Zio Uptime
  theme: dark
