owner: ziodotsh
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
    # Servers
  - name: "Server DE01 (Hetzner)"
    url: https://de01.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-germany_1f1e9-1f1ea.png
  - name: "Server GB01 (Virgin Media)"
    url: https://gb01.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-united-kingdom_1f1ec-1f1e7.png
  - name: "Server GB02 (KCOM)"
    url: https://gb02.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-united-kingdom_1f1ec-1f1e7.png
  - name: "Server HTZ001 (Hetzner)"
    url: https://htz001.zio.sh
    icon: https://emojipedia-us.s3.amazonaws.com/source/skype/289/flag-germany_1f1e9-1f1ea.png
    __dangerous__insecure: true

    # Websites
  - name: Cloud (Nextcloud)
    url: https://cloud.zio.sh
  - name: Git (Gitea)
    url: https://git.zio.sh
    icon: https://git.zio.sh/assets/img/logo.svg
  - name: Mail
    url: https://mail.zio.sh
  - name: OSTree Repo
    url: https://ostree.zio.sh
  - name: ZNC
    url: https://znc.zio.sh
    
    ## External
    # - name: Hetzner Robot
    #   url: robot.your-server.de

status-website:
  cname: uptime.zio.sh
  css: >
    .live-status > article:nth-child(4) { margin-bottom: 1em; }
  name: Zio Uptime
  theme: dark
