owner: ziodotsh
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
    # Servers
  - name: DE01 [🔌 ICMP]
    check: "tcp-ping"
    url: de01.zio.sh
    port: 7
  - name: GB01 [🔌 ICMP]
    check: "tcp-ping"
    url: gb01.zio.sh
    port: 7
  - name: GB02 [⌨️ SSH]
    check: "tcp-ping"
    url: gb02.zio.sh
    port: 20222

    # Services
  - name: Zio Git (Gitea) [🔗 HTTPS]
    url: https://git.zio.sh

    # Websites
  - name: Sodalite [🔗 HTTPS]
    url: https://sodalite.rocks

status-website:
  cname: uptime.zio.sh
  name: Zio Uptime

# Emojis
# 🔗 HTTP/HTTPS
# 🔌 ICMP
# ⌨️ SSH
