owner: ziodotsh
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
    # 🔌 Servers
  - name: "🇩🇪 Zio DE01 (Hetzner)"
    check: "tcp-ping"
    url: https://de01.zio.sh
    port: 22
  - name: "🇬🇧 Zio GB01 (Virgin Media)"
    check: "tcp-ping"
    url: https://gb01.zio.sh
    port: 2222
  - name: "🇬🇧 Zio GB02 (KCOM)"
    check: "tcp-ping"
    url: https://gb02.zio.sh
    port: 20222
  - name: "🇳🇱 Zio NL01 (Scaleway)"
    check: "tcp-ping"
    url: https://nl01.zio.sh
    port: 22

    # ⚙️ Services
  - name: Zio Git (Gitea)
    url: https://git.zio.sh

    # 🔗 Websites
  - name: Sodalite
    url: https://sodalite.rocks
  - name: Sodalite ➔ Git
    url: https://git.sodalite.rocks
  - name: Sodalite ➔ OSTree Repository
    url: https://ostree.sodalite.rocks

status-website:
  cname: uptime.zio.sh
  css: ".live-status > article:nth-child(4) { margin-bottom: 1em; }"
  name: Zio Uptime
